server:
  port: 8301
  servlet:
    path: /
spring:
  application:
    name: suntion-sms
eureka:
  client:
    service-url:
      defaultZone: http://suntion.cc:8101/eureka
    healthcheck:
      enabled: true
  instance:
    instance-id: suntion-sms8301
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
info:
  build.artifactId: $project.artifactId$
  build.version: $project.version$
