server:
  port: 8302
  servlet:
    path: /
spring:
  application:
    name: suntion-sms
eureka:
  client:
    service-url:
      defaultZone: http://suntion-eureka-8101:8101/eureka
  instance:
    instance-id: suntion-sms8302
    prefer-ip-address: true
info:
  build.artifactId: $project.artifactId$
  build.version: $project.version$