server:
  port: 8101
spring:
  application:
    name: suntion-eureka-8101
eureka:
  instance:
    hostname: suntion-eureka-8101
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8102/eureka/