server:
  port: 8301
  servlet:
    path: /
spring:
  application:
    name: suntion-sms
eureka:
  client:
    service-url:
      defaultZone: http://suntion.cc:8101/eureka
  instance:
    instance-id: suntion-sms8301
    prefer-ip-address: true
info:
  build.artifactId: $project.artifactId$
  build.version: $project.version$