server:
    port: 8090
spring:
    application:
        name: suntion-gateway
    cloud:
        gateway:
            routes:
                -   id: suntion-sms
                    uri: lb://suntion-sms
                    predicates:
                        - Path=/sms/**
            discovery:
                locator:
                    lowerCaseServiceId: true
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8101/eureka