server:
    port: 8030
    servlet:
        path: /
logging:
    path: /var/log/${spring.application.name}
spring:
    application:
        name: suntion-bankcard
    profiles:
        active: ${active.profile}
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8761/eureka
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 4000